name: Check Nested Virtualization Support

on:
  workflow_dispatch:

jobs:
  check-nested-virt:
    runs-on: windows-11-arm
    steps:
      - name: Check virtualization firmware support (detailed)
        run: |
          Get-ComputerInfo -Property "HyperV*"
      - name: Check VirtualizationFirmwareEnabled via CIM
        run: |
          $enabled = Get-CimInstance -ClassName Win32_Processor | Select-Object -ExpandProperty VirtualizationFirmwareEnabled
          Write-Host "VirtualizationFirmwareEnabled (CIM): $enabled"
      - name: List all Win32_Processor fields via CIM
        shell: pwsh
        run: |
          $cpuInfo = Get-CimInstance -ClassName Win32_Processor
          foreach ($property in $cpuInfo.PSObject.Properties) {
            Write-Host "$($property.Name): $($property.Value)"
          }

